version: '3'

services:
  mysql:
    platform: linux/arm64
    container_name: bank_db
    image: mysql/mysql-server:8.0.26
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "bank_db"
      MYSQL_USER: "bank_db"
      MYSQL_PASSWORD: "bank_db"
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"