spring:
  h2:
    console :
      enabled: true

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true


jwt :
  headers: Authorization
  secretKey: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  expiration: 300000