
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/jaeilBankDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
server:
  port: 8080
---
spring:
#  h2:
#    console :
#      enabled: true

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true


jwt :
  headers: Authorization
  secretKey: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  expiration: 9600000