spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/bank_db?&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bank_db
    password: bank_db
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always

#---
#spring:
#  config:
#    activate:
#      on-profile: test